### ISSUE TITLE
Split expo and expo go

### ISSUE THREAD

**Issue by jpudysz** [react-native-community/directory#1106]
Hello,

I believe you should introduce two separate flags for Expo: one for Expo Go and another for the Expo Dev Client.

Currently, in the metadata, there is a generic “Expo” flag, which appears to default to "Expo Go" label.

However, this can be misleading. Some may confirm support for Expo but not for Expo Go. In such instances, they should remove the Expo flag entirely to avoid confusion and potential new issues in their repositories.

For instance, with Unistyles, I no longer support Expo Go, but I don’t want to remove “Expo” from the directory.

**Comment by Simek** [comment]
Hello @jpudysz, thanks for the feedback. 👍 

A bit more on that topic can be found on the [Expo doc page](https://docs.expo.dev/workflow/using-libraries/#third-party-libraries) about using libraries, but TL/DR:
> Any library that is compatible with React Native is compatible with the Expo project when you create a [development build](https://docs.expo.dev/workflow/overview/#development-builds). However, it may not be compatible with the [Expo Go](https://expo.dev/expo-go) app.

And this is a reason why "Expo Go" flag exist, and there is no "Expo" flag, since when using development client (which is the recommended workflow for a while), every module which support one, or both, of native platforms will work with Expo. This means that we would need to add "Expo" label to nearly every library (besides some out-of-tree only cases) which is listed in the directory, which we believe would not improve the clarity.

We also believe that nowadays Expo users can simplify the thinking of compatibility to "if this library works with React Native? yes? than it will work with Expo" from a bit more complicated days of eject and managed flow. 😉

**Comment by jpudysz** [comment]
Got it!

Then, IMO "Expo" metadata should resolve to the "Expo" label, not "Expo Go" 😅

You mentioned that every library compatible with React Native is also compatible with Expo, but it might not be compatible with Expo Go.

If something may not be compatible with a subset of apps, I would use the generic label "Expo" to let the user discover its availability. Otherwise, setting "Expo" metadata to true and presenting it as "Expo Go" might be misleading, even though it’s accurate for dev clients.

**Comment by Simek** [comment]
We have shipped the flag rename, so it now reflect the actual meaning of it a bit clearer, hope this helps with confusion.

Also thank you so much for pointing this out, and an interesting discussion which lead to those changes. 🙏 

If there are anything else you see we can improve, feel free to open an another issue!

**Comment by jpudysz** [comment]
Wow @Simek what a massive PR 🔥 thank you for considering my proposal!
