### ISSUE TITLE
Wrong "unmaintained" label

### ISSUE THREAD

**Issue by BrodaNoel** [react-native-community/directory#1376]
I was checking that my library, https://reactnative.directory/?search=duix, which is maintained, is being shown as `unmaintained`, even considering that it is not defined as unmaintained in the https://github.com/react-native-community/directory/blob/main/react-native-libraries.json file.

```
  {
    "githubUrl": "https://github.com/BrodaNoel/duix",
    "ios": true,
    "android": true,
    "web": true,
    "expoGo": true,
    "newArchitecture": true
  },
```

Or should I add the `unmaintained: false` attribute?

**Comment by Simek** [comment]
Hey @BrodaNoel, 

We mark libraries automatically as "unmaintained" if there was no code related activity in the project repository in the last two years:
* https://github.com/react-native-community/directory/blob/0b0968db7ff4927ba400532c68cdfce642eaf38d/scripts/build-and-score-data.js#L65

The latest commit you have pushed few hours ago fixed the categorization already. The "unmaintained" label to that point was correct according to the logic, since the second to last commit was made in April 2022. 

![Screenshot 2024-11-19 at 11 06 59](https://github.com/user-attachments/assets/4f24e0e5-aec3-47f4-bda8-db5da07f86b7)
