### ISSUE TITLE
Favicon not displaying on Safari

### ISSUE THREAD

**Issue by CDeLeon94** [react-native-community/directory#1415]
Safari 18.1 (19619.2.8.111.5, 19619) on MacOS 14.7

![image](https://github.com/user-attachments/assets/46e7ac4f-9d7a-47e8-b247-5e96149070a9)

**Comment by Simek** [comment]
Hello @CDeLeon94, thanks for the report! 👍 

I was able to reproduce this on one of my machines, but not on most of them. I think that the root cause for that is browser caching. Have made a small PR tweaking approach to the favicons, and forcing browsers to invalidate previous cache which should fix the issue.

Please let me know if you still cannot see the favicon a short while after the PR lands!
