### ISSUE TITLE
[Discussion] Rebrand to reactnative.directory and redesign

### ISSUE THREAD

**Issue by brentvatne** [react-native-community/directory#190]
Want to help out with rebranding to react.native.directory? This is the thread for you! Share your ideas or mockups or whatever here!

**Comment by jonsamp** [comment]
I made a rebranded design for this directory.

The main goals were to:
- Make this directory feel more like the [react native docs](https://facebook.github.io/react-native/docs/getting-started), so that it feels more like an "official" directory.
- Make it clearer how to filter and sort search results.
- Make a clearer call to action to add a library to the directory.

I'd love feedback about what you like and what you don't. Below is a screenshot, in addition to a figma link.

<img width="2555" alt="design" src="https://user-images.githubusercontent.com/6455018/73678795-1aa87b80-4687-11ea-853e-6b1716a203f4.png">

Figma link: https://www.figma.com/file/Ihj8oQb4jF3WqDVLddN0LJ/react-native-directory?node-id=2%3A115

**Comment by stmoy** [comment]
@jonsamp - Love this! Great job!

A few thoughts:
- As we start standing up RN for Mac, we'll need that to be one of the options under Platforms. There might also be others?
- The "topics" section on today's version of native.directory has **a ton** of entries, and I'm not actually sure how worthwhile they are. It's basically just another list of all of the modules in the directory. Thoughts on removing that section? 
- Would it be worthwhile to include screenshots/pictures from the module repo? For example, [react-native-camera](https://github.com/react-native-community/react-native-camera) has an animated gif showing the camera component in action. Adding an image might help users quickly find the UI affordances/controls that they are looking for.
- The [react-native docs](https://facebook.github.io/react-native/) have a search field - could we integrate into that search field? 
- Double checking: I assume that clicking on the search result takes the user to the relevant GitHub repo as it does today?

**Comment by brentvatne** [comment]
> As we start standing up RN for Mac, we'll need that to be one of the options under Platforms. There might also be others?

absolutely, this should be easy to add to the list of platforms

> The "topics" section on today's version of native.directory has a ton of entries, and I'm not actually sure how worthwhile they are. It's basically just another list of all of the modules in the directory. Thoughts on removing that section?

agreed, I think we could make better use of screen real estate by removing this

> The react-native docs have a search field - could we integrate into that search field?

yup, we do this already on expo.io for native.directory

<img width="1106" alt="Screen Shot 2020-02-07 at 14 29 42" src="https://user-images.githubusercontent.com/90494/74070584-4d6bb000-49b6-11ea-8618-92a5a0203a4a.png">

> Would it be worthwhile to include screenshots/pictures from the module repo? For example, react-native-camera has an animated gif showing the camera component in action. Adding an image might help users quickly find the UI affordances/controls that they are looking for.

we do this currently on native directory and i think we could continue doing the same thing, cc @jonsamp for thoughts

<img width="967" alt="Screen Shot 2020-02-07 at 14 32 07" src="https://user-images.githubusercontent.com/90494/74070717-ad625680-49b6-11ea-985c-4f2c5c868d35.png">

we might want to let people opt in to providing images manually in some kind of package metadata rather than depending on us extracting from readme

> Double checking: I assume that clicking on the search result takes the user to the relevant GitHub repo as it does today?

that's the plan, I don't think it's necessary for us to have a separate page for each, but willing to be convinced

<hr />

@stmoy - do you have access to any design resources internally at msft that could help us iterate on the logo?

**Comment by stmoy** [comment]
> do you have access to any design resources internally at msft that could help us iterate on the logo?

I'll ask around. For now, lets assume "no" and be pleasantly surprised if we find one. Maybe the community has ideas too? FWIW, I think the current proposal above would sufficiently get the job done.

**Comment by leonardoelias** [comment]
I think about some points:

1. We could have a search box, just like Gastby, without many filters;

![Captura de Tela 2020-02-10 às 19 55 13](https://user-images.githubusercontent.com/1995213/74198158-88344900-4c3f-11ea-97ee-dfd9e1979c40.png)

2. Something like npm, in which the navigation bar with the search term is used more;
![Captura de Tela 2020-02-10 às 19 58 32](https://user-images.githubusercontent.com/1995213/74198287-bdd93200-4c3f-11ea-89f8-56cd9f94fa57.png)

3. In the react-native documentation, the sidebar and gray. I like it better;
![Captura de Tela 2020-02-10 às 19 58 58](https://user-images.githubusercontent.com/1995213/74198361-ebbe7680-4c3f-11ea-91da-27af9cf4bc4e.png)

-----

What will the screen look like to send a package ?

**Comment by gbechtold** [comment]
Hey Guys, if this task is still vacant I'm here to provide you a couple of proposals. 
Do you have any requirements what direction you're looking into?

**Comment by jonsamp** [comment]
Hey @gbechtold, thanks for reaching out! We had a meeting where we decided that [this design](https://user-images.githubusercontent.com/6455018/73678795-1aa87b80-4687-11ea-853e-6b1716a203f4.png) was the direction we want to go. The goal is to make this directory look/feel more like the react-native docs, so that it all feels like one consistent ecosystem. 

There's also a designer at Microsoft gave me some feedback on that design and we're iterating on it, and I'm about to build it.

If you have specific feedback however, I'm always open to it!

**Comment by gbechtold** [comment]
Hello @jonsamp 
Thats perfect. Thank you for letting me know.
I was already curious about your future route. 
Keep up the good work. 

Best regards, 
Guntram

**Comment by jonsamp** [comment]
The updated design is now live 🎉 You can see the design figma here: https://www.figma.com/file/Ihj8oQb4jF3WqDVLddN0LJ/react-native-directory?node-id=0%3A1

Closing this issue.
