### ISSUE TITLE
Webex compatibility with react-native

### ISSUE THREAD

**Issue by rajitha123k** [react-native-community/directory#743]
Hi, I dont see webex in the third party library, can I still use webex js sdk in react native expo and embed webex video calling in my app?

**Comment by Simek** [comment]
Hi @rajitha123k, the answer might depends on the code used in the SDK, not all compatible libraries are listed in directory, since it's OSS maintained and focuses only on the open source projects. 🙂 

I think you should just try it or ask about the compatibility with React Native and Expo in the package repository:
* https://github.com/webex/webex-js-sdk

**Comment by rajitha123k** [comment]
Thank you so much, if webex js sdk is not compliant, is there any way I can add webex in any other way?

**Comment by Simek** [comment]
As I have said before, everything depends on the code used in the SDK. I'm sorry but I'm totally not familiar with Webex SDK, so I'm not able to answer your question.

**Comment by rajitha123k** [comment]
Okay, thank you so much!
