### ISSUE TITLE
Is react-native-bluetooth-escpos-printer compatible with expo go?

### ISSUE THREAD

**Issue by aakashgupta0205** [react-native-community/directory#979]
I am trying to connect to a bluetooth thermal printer in my expo go app. I came across [react-native-bluetooth-escpos-printer](https://github.com/januslo/react-native-bluetooth-escpos-printer) plugin. Is it compatible with expo go?

**Comment by Simek** [comment]
Hello @aakashgupta0205, I'm not familiar with this library, but after quick look at the code it looks like Expo Go is not supported, however, you can use any React Native library while using `expo-dev-client` in the development process instead of Expo Go app:
* https://docs.expo.dev/develop/development-builds/introduction/

**Comment by raajnadar** [comment]
we have a production application and yes we need expo dev client as we need to do some native changes and we don't have a configuration plugin from the maintainer

**Comment by detanx** [comment]
You can use this [expo-react-native-bluetooth-escpos-printer](https://github.com/detanx/expo-react-native-bluetooth-escpos-printer).

**Comment by Simek** [comment]
Closing this as answered!
